zenstruck_foundry:
  # Whether to auto-refresh proxies by default (https://github.com/zenstruck/foundry#auto-refresh)
  auto_refresh_proxies: false

  # Configure faker to be used by your factories.
  faker:
    # Change the default faker locale.
    locale: fr_FR # Example: fr_FR

    # Customize the faker service.
    service: null # Example: my_faker

  # Configure the default instantiator used by your factories.
  instantiator:
    # Whether or not to call an object's constructor during instantiation.
    without_constructor: false

    # Whether or not to allow extra attributes.
    allow_extra_attributes: false

    # Whether or not to skip setters and force set object properties (public/private/protected) directly.
    always_force_properties: false

    # Customize the instantiator service.
    service: null # Example: my_instantiator
